# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb57d29594928abbdf9ea3b2f3717e77993305a91ffa51a95110fb6a341a7eb0880c99f7ea576299baacfa0ab7bb6130b93593067a9dfe835d66ae2b60b545f3

test:
  secret_key_base: eb78e32453ff2a57893ff8028d34d04953f16e6f6101b564616ae66359eb440011d92facf85023b3918f4ab19b335f1e87bb3de8dc10e0bd16df9550b44ca124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
